export type ComponentDocumentation = Readonly<{
  group: "layout" | "typography" | "components" | "editor" | "utilities";
  demo:
    | "buttons"
    | "forms"
    | "navigation"
    | "overlays"
    | "status"
    | "surfaces"
    | "layouts"
    | "editor"
    | "outline"
    | "shell"
    | "scaffold"
    | "theme"
    | "legal";
  samples: readonly string[];
  exports: readonly string[];
  description: string;
  usage: string;
}>;

const doc = (
  group: ComponentDocumentation["group"],
  demo: ComponentDocumentation["demo"],
  samples: readonly string[],
  exports: readonly string[],
  description: string,
  usage: string,
): ComponentDocumentation => ({ group, demo, samples, exports, description, usage });

export const componentDocs = {
  Box: doc(
    "layout",
    "layouts",
    ["Box"],
    ["Box"],
    "A container for shared padding and display rules.",
    '<Box p="4"><p>Content with padding</p></Box>',
  ),
  Flex: doc(
    "layout",
    "layouts",
    ["Flex", "Responsive Flex"],
    ["Flex"],
    "Arrange children in a row or column with alignment and gaps.",
    '<Flex gap="3" align="center" wrap="wrap"><Button>Save</Button><Button variant="outline">Cancel</Button></Flex>',
  ),
  Grid: doc(
    "layout",
    "layouts",
    ["Grid"],
    ["Grid"],
    "Arrange children in responsive rows and columns.",
    '<Grid columns={{ initial: "1", md: "2", lg: "4" }} gap="3"><p>One</p><p>Two</p><p>Three</p><p>Four</p></Grid>',
  ),
  Container: doc(
    "layout",
    "layouts",
    ["Container"],
    ["Container"],
    "Constrain content to a shared measure.",
    '<Container size="2" px="4"><p>Document content</p></Container>',
  ),
  Section: doc(
    "layout",
    "layouts",
    ["Section"],
    ["Section"],
    "Set vertical rhythm between page regions.",
    '<Section size="1"><p>Section content</p></Section>',
  ),
  AppShell: doc(
    "layout",
    "shell",
    ["Responsive shell"],
    ["AppShell"],
    "Application navigation that responds to its container.",
    '<AppShell activeItemId="home" sections={[{ id: "main", items: [{ id: "home", label: "Home", target: "#/home" }] }]}><p>Application content</p></AppShell>',
  ),
  PageScaffold: doc(
    "layout",
    "scaffold",
    ["Page structure"],
    ["PageScaffold"],
    "Shared page heading, actions, content width, and safe gutters.",
    '<PageScaffold title="Projects" description="Your shared work."><p>Page content</p></PageScaffold>',
  ),
  ListDetail: doc(
    "layout",
    "layouts",
    ["List and detail"],
    ["ListDetail"],
    "A responsive list and detail composition.",
    "<ListDetail list={<p>Items</p>} detail={<p>Selected item</p>} detailVisible={false} onBack={() => {}} />",
  ),
  Link: doc(
    "typography",
    "navigation",
    ["Link"],
    ["Link"],
    "Accessible navigation within prose and supporting copy.",
    '<Link href="#/projects">View projects</Link>',
  ),
  Alert: doc(
    "components",
    "status",
    ["Alerts"],
    ["Alert", "AlertTitle"],
    "Inline feedback with a semantic tone.",
    '<Alert tone="warning"><AlertTitle>Review required</AlertTitle>Check the details before continuing.</Alert>',
  ),
  AlertDialog: doc(
    "components",
    "overlays",
    ["Alert dialog"],
    ["AlertDialog"],
    "A modal confirmation that requires an explicit response.",
    '<AlertDialog open={open} onOpenChange={setOpen} title="Delete item?" description="This cannot be undone." confirmLabel="Delete" onConfirm={deleteItem} />',
  ),
  Badge: doc(
    "components",
    "status",
    ["Badges"],
    ["Badge", "BadgeDot"],
    "Compact status labels and inline tags.",
    '<Badge tone="success"><BadgeDot />Ready</Badge>',
  ),
  Breadcrumbs: doc(
    "components",
    "navigation",
    ["Breadcrumbs"],
    ["Breadcrumbs"],
    "Expose ancestors and the current location.",
    '<Breadcrumbs items={[{ label: "Projects", href: "#/projects" }, { label: "Design system" }]} />',
  ),
  Button: doc(
    "components",
    "buttons",
    ["Variants", "Sizes", "States"],
    ["Button"],
    "Action hierarchy, sizes, loading, and disabled states.",
    '<Button variant="primary" size="md" onClick={save}>Save changes</Button>',
  ),
  Card: doc(
    "components",
    "surfaces",
    ["Card variants", "Compact card title"],
    ["Card", "CardHeader", "CardTitle", "CardDescription", "CardContent", "CardFooter"],
    "A surface with composable heading, content, and actions.",
    "<Card><CardHeader><CardTitle>Project</CardTitle><CardDescription>Shared work</CardDescription></CardHeader><CardContent>Details</CardContent><CardFooter><Button>Open</Button></CardFooter></Card>",
  ),
  Checkbox: doc(
    "components",
    "forms",
    ["Checkbox"],
    ["Checkbox"],
    "Independent selection with checked and disabled states.",
    '<Checkbox defaultChecked label="Include references" />',
  ),
  Combobox: doc(
    "components",
    "forms",
    ["Combobox"],
    ["Combobox"],
    "Filter a set of options by typing.",
    '<Field><FieldLabel>Project</FieldLabel><Combobox options={[{ label: "Research", value: "research" }]} placeholder="Find a project" /></Field>',
  ),
  ContextMenu: doc(
    "components",
    "overlays",
    ["Context menu"],
    ["ContextMenu"],
    "Actions anchored to a pointer or long press.",
    '<ContextMenu items={[{ label: "Copy", onSelect: copy }]}><p>Right-click here</p></ContextMenu>',
  ),
  Dialog: doc(
    "components",
    "overlays",
    ["Dialog"],
    ["Dialog"],
    "A controlled modal with heading, body, and actions.",
    '<Dialog open={open} onOpenChange={setOpen} title="Edit item" actions={[{ label: "Close" }]}><p>Dialog content</p></Dialog>',
  ),
  DropdownMenu: doc(
    "components",
    "overlays",
    ["Dropdown menu"],
    ["DropdownMenu"],
    "A trigger and an accessible menu of actions.",
    '<DropdownMenu label="Actions" items={[{ label: "Rename", onSelect: rename }]} />',
  ),
  EmptyState: doc(
    "components",
    "status",
    ["Empty state"],
    ["EmptyState"],
    "Explain missing content and offer the next action.",
    '<EmptyState title="No projects" description="Create your first project." action={<Button>Create project</Button>} />',
  ),
  Field: doc(
    "components",
    "forms",
    ["Text field"],
    ["Field", "FieldLabel", "FieldDescription", "FieldError"],
    "Connect a label, description, validation message, and input.",
    '<Field><FieldLabel>Name</FieldLabel><Input name="name" /><FieldDescription>Visible to collaborators.</FieldDescription></Field>',
  ),
  Icon: doc(
    "components",
    "overlays",
    ["Icons"],
    ["Icon"],
    "Named icons with sizing and accessible labels.",
    '<Icon name="copy" label="Copy" />',
  ),
  Input: doc(
    "components",
    "forms",
    ["Text field"],
    ["Input"],
    "Single-line text input with native input attributes.",
    '<Field><FieldLabel>Name</FieldLabel><Input placeholder="Project name" name="name" /></Field>',
  ),
  NavItem: doc(
    "components",
    "navigation",
    ["Navigation items"],
    ["NavItem", "NavRailItem", "NavSectionLabel"],
    "Shared links for sidebars and compact navigation rails.",
    '<nav aria-label="Projects"><NavSectionLabel>Workspace</NavSectionLabel><NavItem href="#/projects" icon="layers" active>Projects</NavItem></nav>',
  ),
  Popover: doc(
    "components",
    "overlays",
    ["Popover"],
    ["Popover"],
    "Non-modal content anchored to a trigger.",
    '<Popover title="Details" trigger={<Button variant="outline">Details</Button>}><p>Additional information</p></Popover>',
  ),
  Progress: doc(
    "components",
    "status",
    ["Progress"],
    ["Progress"],
    "A labelled indicator for measurable work.",
    '<Progress label="Uploading" value={64} />',
  ),
  RadioGroup: doc(
    "components",
    "forms",
    ["Radio group"],
    ["RadioGroup", "Radio"],
    "Choose exactly one option from a visible set.",
    '<RadioGroup aria-label="Visibility" defaultValue="private"><Radio value="private" label="Private" /><Radio value="shared" label="Shared" /></RadioGroup>',
  ),
  Select: doc(
    "components",
    "forms",
    ["Select"],
    ["Select"],
    "Choose from a fixed set of options.",
    '<Field><FieldLabel>Theme</FieldLabel><Select options={[{ label: "Forest", value: "forest" }, { label: "Slate", value: "slate" }]} defaultValue="forest" /></Field>',
  ),
  Separator: doc(
    "components",
    "surfaces",
    ["Separator"],
    ["Separator"],
    "A quiet horizontal or vertical boundary.",
    "<Separator />",
  ),
  Skeleton: doc(
    "components",
    "status",
    ["Skeleton"],
    ["Skeleton"],
    "Hold the geometry of known content while loading.",
    '<Skeleton width="short" />',
  ),
  Spinner: doc(
    "components",
    "status",
    ["Spinner"],
    ["Spinner"],
    "Accessible feedback for short, unmeasurable waits.",
    '<Spinner label="Loading" tone="primary" />',
  ),
  SuggestionList: doc(
    "components",
    "navigation",
    ["Suggestion list"],
    ["SuggestionList", "useSuggestionList"],
    "Keyboard-driven completion for host-owned search.",
    'const controller = useSuggestionList({ items, sessionKey, onAccept, onDismiss });\n<SuggestionList controller={controller} items={items} panelRef={panelRef} heading="Suggestions" label="Suggestions" emptyLabel="No matches" />',
  ),
  Switch: doc(
    "components",
    "forms",
    ["Switch"],
    ["Switch"],
    "Toggle a setting that applies immediately.",
    '<Switch defaultChecked label="Enable sync" />',
  ),
  Tabs: doc(
    "components",
    "navigation",
    ["Tabs"],
    ["Tabs", "TabsList", "Tab", "TabPanel"],
    "Peer views within one subject, with keyboard navigation.",
    '<Tabs defaultValue="overview"><TabsList aria-label="Project views"><Tab value="overview">Overview</Tab></TabsList><TabPanel value="overview">Project details</TabPanel></Tabs>',
  ),
  Textarea: doc(
    "components",
    "forms",
    ["Textarea"],
    ["Textarea"],
    "Multiline prose input with native textarea attributes.",
    '<Field><FieldLabel>Notes</FieldLabel><Textarea name="notes" rows={4} /></Field>',
  ),
  Toast: doc(
    "components",
    "overlays",
    ["Toast"],
    ["ToastProvider", "toast"],
    "Transient notifications with priority and optional actions.",
    '<ToastProvider><Button onClick={() => toast({ title: "Saved", tone: "success" })}>Save</Button></ToastProvider>',
  ),
  Tooltip: doc(
    "components",
    "overlays",
    ["Tooltip"],
    ["TooltipProvider", "Tooltip"],
    "Concise hints on pointer hover and keyboard focus.",
    '<TooltipProvider><Tooltip content="Copy identity"><Button aria-label="Copy identity" size="icon"><Icon name="copy" /></Button></Tooltip></TooltipProvider>',
  ),
  OutlineTree: doc(
    "editor",
    "outline",
    ["Node outline"],
    ["OutlineTree", "OutlineBullet", "OutlineBulletDot", "OutlineRowProgress"],
    "Hierarchical content, selection, editing, and host-owned commands.",
    '<OutlineTree label="Document outline" items={items} expandedKeys={expandedKeys} onExpandedChange={onExpandedChange} presentation={presentation} />',
  ),
  NodeEditor: doc(
    "editor",
    "editor",
    ["Node heading", "Node table", "Inline content"],
    ["NodeEditor"],
    "Coordinate editable regions around host-owned data.",
    '<NodeEditor><NodeTable label="Components" columns={[{ key: "name", heading: "Name" }]} rows={rows} /></NodeEditor>',
  ),
  NodeHeading: doc(
    "editor",
    "editor",
    ["Node heading"],
    ["NodeHeading"],
    "An editable document heading within a NodeEditor.",
    "<NodeEditor><NodeHeading target={target} editing={editing} onEmptyBody={onEmptyBody} onEnter={onEnter} /></NodeEditor>",
  ),
  NodeTable: doc(
    "editor",
    "editor",
    ["Node table"],
    ["NodeTable", "OutlineEmptyChild"],
    "Host-owned columns and rows with a composable footer.",
    '<NodeEditor><NodeTable label="Components" columns={[{ key: "name", heading: "Name" }]} rows={rows} /></NodeEditor>',
  ),
  OutlineInlineContent: doc(
    "editor",
    "editor",
    ["Inline content"],
    ["OutlineInlineContent"],
    "Render structured inline content outside an editable region.",
    '<OutlineInlineContent content={[{ type: "text", text: "Shared content" }]} />',
  ),
  CairnTheme: doc(
    "utilities",
    "theme",
    ["Theme preview"],
    ["CairnTheme", "resolveTheme"],
    "Configure an application root with a built-in or validated custom theme.",
    '<CairnTheme theme="slate" appearance="dark"><Button>Save</Button></CairnTheme>',
  ),
  LegalPage: doc(
    "utilities",
    "legal",
    ["Bundled font licenses"],
    ["LegalPage"],
    "Display the bundled font attribution and license text.",
    '<LegalPage backHref="#/settings" backLabel="Return to settings" />',
  ),
} as const satisfies Readonly<Record<string, ComponentDocumentation>>;

export type CatalogComponentId = keyof typeof componentDocs;

export function componentPath(id: CatalogComponentId): string {
  return `${componentDocs[id].group}/${id.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase()}`;
}
