const shadow = (...layers) => layers.map((layer) => `${layer} light-dark(var(--black-a2), var(--black-a7))`).join(", ");

// Paper, ink, and forest green; flat stationary surfaces, shadows only on floating layers.
export default {
  label: "Forest",
  description: "Calm paper surfaces and a deep forest accent for everyday tools.",
  colors: {
    accent: { light: "#244C39", dark: "#86DBAE" },
    gray: { light: "#5F665F", dark: "#8FA099" },
    background: { light: "#F6F7F5", dark: "#0B1110" },
    info: { light: "#2F5E9E", dark: "#8FB8E8" },
    success: { light: "#3F7D55", dark: "#67D498" },
    warning: { light: "#8A6116", dark: "#F0C96E" },
    danger: { light: "#B4403B", dark: "#FF918C" },
    // Forest tints stay close to the paper and pair them with deep ink-toned text.
    toneSteps: {
      subtle: ["a2", "a3"],
      "subtle-hover": ["a3", "a4"],
      "subtle-active": ["a4", "a5"],
      border: "a5",
      text: ["12", "11"],
    },
  },
  tokens: {
    "font-interface": '"HarmonyOS Sans SC", system-ui, sans-serif',
    "font-document": '"HarmonyOS Sans SC", system-ui, sans-serif',
    "font-code": '"JetBrains Mono", SFMono-Regular, Consolas, monospace',
    "weight-regular": "400",
    "weight-medium": "500",
    "weight-semibold": "600",
    "weight-bold": "700",
    "heading-letter-spacing": "-0.02em",
    "text-caption-size": "12px",
    "text-caption-line-height": "18px",
    "text-label-size": "13px",
    "text-label-line-height": "20px",
    "text-body-size": "14px",
    "text-body-line-height": "22px",
    "text-body-large-size": "16px",
    "text-body-large-line-height": "26px",
    "text-document-size": "15px",
    "text-document-line-height": "21px",
    "text-title-small-size": "19px",
    "text-title-small-line-height": "26px",
    "text-title-size": "22px",
    "text-title-line-height": "30px",
    "text-page-title-size": "28px",
    "text-page-title-line-height": "36px",
    "text-display-size": "36px",
    "text-display-line-height": "44px",
    "space-1": "4px",
    "space-2": "8px",
    "space-3": "12px",
    "space-4": "16px",
    "space-5": "24px",
    "space-6": "32px",
    "space-7": "40px",
    "space-8": "48px",
    "space-9": "64px",
    "radius-selection": "4px",
    "radius-indicator": "6px",
    "radius-control": "8px",
    "radius-item": "8px",
    "radius-panel": "12px",
    "radius-card": "16px",
    "radius-dialog": "16px",
    "radius-pill": "999px",
    "border-width": "1px",
    "control-height-sm": "32px",
    "control-height-md": "40px",
    "control-height-lg": "48px",
    "control-padding-sm": "12px",
    "control-padding-md": "16px",
    "control-padding-lg": "24px",
    "focus-ring-width": "2px",
    "focus-ring-offset": "2px",
    "disabled-opacity": "0.5",
    "elevation-control": "none",
    "elevation-card": "none",
    "elevation-popover": shadow("0 4px 6px -1px", "0 2px 4px -2px"),
    "elevation-dialog": shadow("0 10px 15px -3px", "0 4px 6px -4px"),
    "elevation-toast": shadow("0 10px 15px -3px", "0 4px 6px -4px"),
    "elevation-tooltip": shadow("0 1px 3px 0", "0 1px 2px -1px"),
    "overlay-backdrop-filter": "none",
    "duration-fast": "120ms",
    "duration-standard": "160ms",
    "duration-panel": "200ms",
    "ease-standard": "cubic-bezier(0.2, 0, 0, 1)",
  },
};
